<?php

declare(strict_types=1);

namespace App\Facades;

use FKS\Abilities\Facade\AbilityFacade as BaseAbilityFacade;

/**
 * NOTICE! This is autogenerated class
 * 
 * Run 'php artisan abilities:generate-facade' to collect all classes implemented AbilitiesResolverInterface and build Facade
 *
 * @method static bool canSeeAllPayments()
 */
class AbilityFacade extends BaseAbilityFacade
{
    public static array $abilities = [
        \App\Services\Payments\Abilities\PaymentAbilities::class => [
            'canSeeAllPayments',
        ],
    ];

    public static function getAbilities(): array
    {
        return static::$abilities;
    }
}